# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc84e08ba9da4f169f23edece60c07f0c1bb14b675d2c6628d7b867e9eba826092dca80669b9041bf66e8682c7a0a9eb3211d980e3ed0a95c7d5decd3a1a62ea

test:
  secret_key_base: 1505bb9a4b10d246ccc8e0d12c4247710ca74e1d015a9413221b612cf319ed75c0b2bd78946f318a8056bb7f2ea64d60de458ae241c305b393f68c63d16efbfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
